import { DescricaoStep } from "../descricao-step";
import type { StepRenderer } from "./types";

export const buildDescricaoStepCtx = (ctx: Parameters<StepRenderer>[0]) => ({
  currentGheName: ctx.currentGheName,
  lastGheNotice: ctx.lastGheNotice,
  searchTerm: ctx.searchTerm,
  setSearchTerm: ctx.setSearchTerm,
  availableCountLabel: ctx.availableCountLabel,
  remainingCount: ctx.remainingCount,
  describedGheCount: ctx.describedGheCount,
  setIsGheModalOpen: ctx.setIsGheModalOpen,
  setIsGheListView: ctx.setIsGheListView,
  isGheListView: ctx.isGheListView,
  importExcelInputRef: ctx.importExcelInputRef,
  handleDescricaoExcelChange: ctx.generalActions.handleDescricaoExcelChange,
  handleAddManualFunction: ctx.generalActions.handleAddManualFunction,
  isImportingExcel: ctx.isImportingExcel,
  excelImportFeedback: ctx.excelImportFeedback,
  groupedFunctions: ctx.groupedFunctions,
  selectedLeftIds: ctx.selectedLeftIds,
  handleSelectionStart: ctx.descricaoInteractions.handleSelectionStart,
  leftListRef: ctx.descricaoInteractions.leftListRef,
  getSelectionStyle: ctx.descricaoInteractions.getSelectionStyle,
  dragOverZone: ctx.descricaoInteractions.dragOverZone,
  handleDragOver: ctx.descricaoInteractions.handleDragOver,
  handleDropToLeft: ctx.descricaoInteractions.handleDropToLeft,
  handleDragLeave: ctx.descricaoInteractions.handleDragLeave,
  handleToggleLeftSelection: ctx.descricaoInteractions.handleToggleLeftSelection,
  handleDragStartLeft: ctx.descricaoInteractions.handleDragStartLeft,
  handleAddSelected: ctx.descricaoInteractions.handleAddSelected,
  deleteFunction: ctx.descricaoInteractions.handleDeleteSelected,
  handleRemoveSelected: ctx.descricaoInteractions.handleRemoveSelected,
  handleCreateNextGhe: ctx.descricaoInteractions.handleCreateNextGhe,
  currentItems: ctx.currentItems,
  functionMap: ctx.functionMap,
  selectedRightIds: ctx.selectedRightIds,
  handleDropToRight: ctx.descricaoInteractions.handleDropToRight,
  rightListRef: ctx.descricaoInteractions.rightListRef,
  handleToggleRightSelection: ctx.descricaoInteractions.handleToggleRightSelection,
  handleDragStartRight: ctx.descricaoInteractions.handleDragStartRight,
  miniInputClass: ctx.miniInputClass,
  handleFuncionarioChange: ctx.descricaoInteractions.handleFuncionarioChange,
  handleRemoveSingle: ctx.descricaoInteractions.handleRemoveSingle,
  handleUpdateFunctionDetails: ctx.descricaoInteractions.handleUpdateFunctionDetails,
  isGheModalOpen: ctx.isGheModalOpen,
  gheFilterId: ctx.gheFilterId,
  setGheFilterId: ctx.setGheFilterId,
  gheGroups: ctx.gheGroups,
  handleSelectGhe: ctx.descricaoInteractions.handleSelectGhe,
  gheSearch: ctx.gheSearch,
  setGheSearch: ctx.setGheSearch,
  inputInlineClass: ctx.inputInlineClass,
  normalizedGheSearch: ctx.normalizedGheSearch,
  filteredAllFunctions: ctx.filteredAllFunctions,
  filteredGheGroupsForList: ctx.filteredGheGroupsForList,
  truncatePreview: ctx.truncatePreview,
  functionAssignments: ctx.functionAssignments,
  assignGheOptions: ctx.assignGheOptions,
  selectBaseClass: ctx.selectBaseClass,
  handleAssignFunction: ctx.descricaoInteractions.handleAssignFunction,
  isInfoModalOpen: ctx.isInfoModalOpen,
  setInfoModalError: ctx.setInfoModalError,
  setIsInfoModalOpen: ctx.setIsInfoModalOpen,
  textareaBaseClass: ctx.textareaBaseClass,
  currentGhe: ctx.currentGhe,
  handleInfoChange: ctx.descricaoInteractions.handleInfoChange,
  infoModalError: ctx.infoModalError,
  handleConfirmInfoModal: ctx.descricaoInteractions.handleConfirmInfoModal,
  infoModalMode: ctx.infoModalMode,
});

export type DescricaoStepCtx = ReturnType<typeof buildDescricaoStepCtx>;

export const renderDescricaoStep: StepRenderer = (ctx) => <DescricaoStep ctx={buildDescricaoStepCtx(ctx)} />;
