export type FixedSection = {
  title: string;
  paragraphs: string[];
};

export const FIXED_SECTIONS_5_TO_18: FixedSection[] = [
  {
    title: "5 - Introdução",
    paragraphs: [
      "Em 12 de março de 2020, a Portaria nº 6.730 da Secretaria Especial de Previdência e Trabalho publicou a publicação da Norma Regulamentadora nº 1 (NR-01), que estabelece as disposições gerais, o campo de aplicação, os termos e as definições comuns às Normas Regulamentadoras (NR) relativas à segurança e saúde no trabalho, além das diretrizes e requisitos para o Gerenciamento de Riscos Ocupacionais (GRO) e as medidas de prevenção em Segurança e Saúde no Trabalho (SST).",
      "Posteriormente, em 27 de agosto de 2024, a Portaria MTE nº 1.419 trouxe uma atualização significativa à NR-01, incluindo os riscos psicossociais no escopo do gerenciamento de riscos ocupacionais. A nova redação exige que as empresas identifiquem, avaliem e implementem medidas para mitigar fatores que possam impactar a saúde mental dos trabalhadores, como sobrecarga de trabalho, assédio moral e outros aspectos organizacionais que influenciam o bem-estar no ambiente laboral. Essas mudanças entram em vigor a partir de 25 de maio de 2025, reforçando a necessidade de uma abordagem mais abrangente para a segurança e saúde no trabalho.",
      "O Gerenciamento de riscos ocupacionais traz como responsabilidade das organizações constituir o Programa de Gerenciamento de Riscos – PGR que por critério da organização pode ser implementado por unidade operacional, setor ou atividade.",
      "O PGR pode ser atendido por sistemas de gestão, desde que estes cumpram as exigências previstas nesta NR e em dispositivos legais de segurança e saúde no trabalho.",
      "O PGR deve contemplar ou estar integrado com planos, programas e outros documentos previstos na legislação de segurança e saúde no trabalho.",
      "O PGR constitui-se numa ferramenta de extrema importância para a segurança e saúde dos empregados, devendo estar articulado com as demais NR, proporcionando identificar as medidas de proteção ao trabalhador a serem implementadas e serve de base para a elaboração do Programa de Controle Médico e Saúde Ocupacional – PCMSO, obrigatório pela NR-7.",
      "Este PGR contém o Inventário de riscos ocupacionais relacionados às atividades existentes na empresa, compreendendo todas as categorias de riscos à segurança e saúde dos trabalhadores e constitui um dos documentos básicos do Programa de Gestão de Riscos, no que diz respeito ao reconhecimento e avaliação de riscos relacionados a agentes físicos, químicos, biológicos, acidentes e ergonômicos, incluindo os fatores de risco psicossociais relacionados ao trabalho.",
      "Atende às exigências da Norma Regulamentadora 09, no que diz respeito ao reconhecimento e avaliação de riscos relacionados às exposições ocupacionais.",
      "Atende às exigências da Norma Regulamentadora 17 – Ergonomia, indicando as condições de trabalho que incluem aspectos relacionados ao levantamento, transporte e descarga de materiais, ao mobiliário dos postos de trabalho, ao trabalho com máquinas, equipamentos e ferramentas manuais, às condições de conforto.",
      "Os dados constantes neste documento servem de base para a elaboração do Plano de Ação de Segurança e Saúde do Trabalho, que contempla as ações de controle a serem mantidas, implementadas ou melhoradas, assim como as atividades de monitoramento das exposições.",
      "Os riscos identificados para cada grupo de trabalhadores expostos irão subsidiar a elaboração ou reformulação do PCMSO.",
      "A organização deve adotar mecanismo para consultar os trabalhadores quanto à percepção de riscos ocupacionais, podendo para este fim ser adotadas as manifestações da Comissão Interna de Prevenção de Acidentes e Assédio - CIPA, quando houver; e comunicar aos trabalhadores sobre os riscos consolidados no inventário de riscos e as medidas de prevenção do plano de ação do PGR.",
      "O empregador deverá garantir que, na ocorrência de riscos nos locais de trabalho que coloquem em situação de grave e iminente risco um ou mais trabalhadores, os mesmos possam interromper de imediato as suas atividades, comunicando o fato ao superior hierárquico direto para as devidas providências.",
      "Comprovada pelo empregador a situação de grave e iminente risco, não poderá ser exigida a volta dos trabalhadores à atividade enquanto não forem tomadas as medidas corretivas.",
    ],
  },
  {
    title: "6 - Objetivo",
    paragraphs: [
      "O PGR tem como objetivo a preservação da saúde e a integridade física dos trabalhadores, através da identificação dos perigos e possíveis lesões ou agravo à saúde, a avaliação dos riscos ocupacionais indicando o nível, e a classificação dos riscos para determinar a necessidade de adoção de medidas de prevenção de acordo com a ordem de prioridade estabelecida na NR-1 subitem 1.4.1 alínea “g”.",
      "Os objetivos deste Inventário de Riscos são:",
      "Caracterizar exposições a todas as condições perigosas e aos agentes potencialmente nocivos – químicos, físicos, biológicos e outros fatores estressores que constituem cargas de trabalho física e mental significativas.",
      "Caracterizar a intensidade e a variação temporal das exposições para todos os trabalhadores – próprios e de contratadas que atuem em atividades dentro dos limites da empresa.",
      "Avaliar os riscos potenciais à segurança e saúde de todos os trabalhadores.",
      "Priorizar e recomendar ações para controlar exposições que representem riscos inaceitáveis e intoleráveis.",
      "Registrar as avaliações ambientais realizadas na empresa.",
      "Comunicar os resultados do processo de levantamento de perigos e avaliação de riscos para todos os trabalhadores envolvidos.",
      "Manter o registro histórico das exposições para todos os trabalhadores de forma que problemas futuros de saúde possam ser analisados e gerenciados com base em informações reais de exposição.",
    ],
  },
  {
    title: "7 - Documento",
    paragraphs: [
      "O PGR deve conter no mínimo os seguintes documentos: o inventário de riscos e plano de ação, a ser elaborado pela organização, respeitados as demais Normas Regulamentadoras, datados e assinados.",
      "Os documentos integrantes do PGR devem estar sempre disponíveis aos trabalhadores interessados ou seus representantes e à Inspeção do Trabalho.",
    ],
  },
  {
    title: "8 - Inventário de Riscos Ocupacionais",
    paragraphs: [
      "Os dados da identificação dos perigos e das avaliações dos riscos ocupacionais devem ser consolidados em um inventário de riscos ocupacionais, que deve contemplar, no mínimo, as seguintes informações:",
      "Caracterização dos processos e ambientes de trabalho;",
      "Caracterização das atividades;",
      "descrição dos perigos, com a identificação das fontes e/ou circunstâncias;",
      "indicação das possíveis lesões ou agravos à saúde decorrentes da exposição dos trabalhadores aos perigos;",
      "indicação dos grupos de trabalhadores expostos aos perigos;",
      "descrição das medidas de prevenção implementadas;",
      "caracterização da exposição dos trabalhadores aos perigos;",
      "dados da análise preliminar ou do monitoramento das exposições a agentes físicos, químicos e biológicos e os resultados da avaliação de ergonomia nos termos da NR-17; e",
      "avaliação dos riscos, incluindo a classificação para fins de elaboração do plano de ação.",
    ],
  },
  {
    title: "9 - Plano de Ação",
    paragraphs: [
      "A organização deve elaborar um plano de ação detalhado, estabelecendo as medidas de prevenção a serem introduzidas, aprimoradas ou mantidas, de acordo com a classificação do nível de risco ocupacional. Esse nível é determinado pela combinação entre a severidade das possíveis consequências das lesões ou agravos à saúde e a probabilidade de sua ocorrência, permitindo a identificação da necessidade de adoção de medidas preventivas. Além disso, o número de trabalhadores potencialmente atingidos deve ser considerado como critério para priorizar as ações. Para garantir a efetividade das medidas de prevenção, o plano de ação deve incluir um cronograma definido, a designação de responsáveis, formas de acompanhamento e mecanismos para aferição dos resultados, assegurando a melhoria contínua das condições de segurança e saúde no trabalho.",
    ],
  },
  {
    title: "10 - Definição das Responsabilidades",
    paragraphs: [
      "DO EMPREGADOR/ RESPONSÁVEL LEGAL:O empregador é o responsável por estabelecer, implementar e assegurar o cumprimento do PGR bem como as demais documentações que o compõe, como atividade permanente da empresa, bem como consultar os trabalhadores quanto à percepção de riscos ocupacionais, podendo para este fim ser adotadas as manifestações da Comissão Interna de Prevenção de Acidentes e Assédio - CIPA, quando houver; comunicar aos trabalhadores sobre os riscos consolidados no inventário de riscos e as medidas de prevenção do plano de ação; adotar medidas necessárias para melhorar o desempenho em SST; O processo de identificação de perigos e avaliação de riscos ocupacionais considerando o disposto nas Normas Regulamentadoras e demais exigências legais de segurança e saúde no trabalho e controle dos riscos.",
      "A organização deverá:",
      "a) evitar ou eliminar os perigos ocupacionais que possam ser originados no trabalho;",
      "b) identificar os perigos e possíveis lesões ou agravos à saúde;",
      "c) avaliar os riscos ocupacionais indicando o nível de risco;",
      "d) classificar os riscos ocupacionais para determinar a necessidade de adoção de medidas de prevenção;",
      "e) implementar medidas de prevenção, de acordo com a classificação de risco e na ordem de prioridade estabelecida na alínea “g” do subitem 1.4.1 da NR-01; e",
      "f) acompanhar o controle dos riscos ocupacionais.",
      "DOS TRABALHADORESOs trabalhadores têm como responsabilidade colaborar e participar na implantação e execução do PGR.",
      "Seguir as orientações recebidas nos treinamentos oferecidos dentro do PGR; e informar ao seu superior hierárquico direto as ocorrências que, a seu julgamento, possam implicar em riscos à saúde dos trabalhadores.",
      "INTEGRAÇÃO COM A CIPAO PGR, suas alterações e complementações deverão ser apresentados e discutidos na Comissão Interna de Prevenção de Acidentes e Assédio - CIPA, quando existente na empresa, de acordo com a NR-5, sendo uma cópia anexada ao livro de ata desta comissão.",
    ],
  },
  {
    title: "11 - Abrangência",
    paragraphs: [
      "Este Programa abrangerá os perigos identificados no ambiente de trabalho da empresa, conforme estabelecido na NR-1 da Portaria 3214/78.",
      "O processo se inicia com a caracterização básica de cada unidade – processo e ambiente de trabalho, força de trabalho e agentes ambientais e estressores. Esses dados servem de base para definir os grupos homogêneos de exposição (GHE) e atividades não rotineiras ou de empresas contratadas, para os quais os riscos serão reconhecidos e avaliados.",
    ],
  },
  {
    title: "12 - Definições",
    paragraphs: [
      "DANOÉ a consequência de um perigo em termos de lesão, doença, ou uma combinação desses.",
      "PERIGOFonte, situação ou ato com potencial para provocar danos humanos em termos de lesão, ou uma combinação dessas.",
      "IDENTIFICAÇÃO DE PERIGOProcesso de reconhecimento que um perigo existe, e de definição de suas características.",
      "RISCOCombinação da probabilidade de ocorrência de um evento perigoso ou exposição com a gravidade da lesão ou doença que pode ser causada pelo evento ou exposição.",
      "AVALIAÇÃO DE RISCOSProcesso de avaliação de risco proveniente de perigo, levando em consideração a adequação de qualquer controle existente, e decidindo se o risco é ou não aceitável.",
      "RISCO ACEITÁVELRisco que foi reduzido a um nível que pode ser tolerado pela empresa, levando em consideração suas obrigações legais e sua própria política de SST.",
      "ESTIMATIVA DE RISCOProcesso para determinar a frequência ou a probabilidade e as consequências de um perigo.",
      "NÍVEL DE AÇÃOÉ o valor, apurado na etapa de avaliação dos riscos, acima do qual deverão ser iniciadas as medidas preventivas de forma a minimizar a probabilidade de que as exposições a agentes ambientais ultrapassem os limites de exposição tais como:",
      "Medições periódicas da exposição ocupacional;",
      "Treinamento dos trabalhadores;",
      "Acompanhamento médico com monitoramentos biológicos apropriados.",
      "Os níveis de ação adotados são aqueles previstos na NR-9:",
      "Agentes Químicos: Metade dos limites de exposição ocupacional adotados.",
      "Ruído: Dose de 0,5 (50% de dose) do limite de tolerância previsto para a jornada de trabalho.",
      "LIMITE DE TOLERÂNCIA Referem-se às concentrações ou intensidades que representam as condições sob as quais se acredita que quase todos os trabalhadores possam estar expostos contínua e diariamente, sem apresentar efeitos adversos à saúde. Referem às concentrações médias máximas que não devem ser ultrapassadas numa jornada.",
      "VALOR TETOConcentração que não pode ser excedida durante nenhum momento da exposição do trabalhador.",
      "GRUPOS HOMOGÊNEOS DE EXPOSIÇÃO (GHE)Para elaboração deste documento adotou-se a definição de Grupo Homogêneo de Exposição (GHE), que corresponde a um grupo de trabalhadores que experimentam exposição semelhante de forma que, o resultado fornecido pela avaliação da exposição de qualquer trabalhador do grupo seja representativo da exposição do restante dos trabalhadores do mesmo grupo.",
      "Um grupo é homogêneo no sentido estatístico, e isso permite que um número relativamente pequeno de amostras possa definir as tendências de exposição de todo o grupo.",
      "Depois de observar e conhecer as exposições, reunir os trabalhadores em grupos que possuem as mesmas chances de exposição a um dado agente. Essa “igualdade” provém do desenvolvimento de rotinas e tarefas essencialmente idênticas ou similares do ponto de vista da exposição.",
      "CONCEITO DE EXPOSTO DE MAIOR RISCO (EMR)O conceito de Exposto de Maior Risco (EMR) é importante para a otimização de ações de Estratégia de Amostragem. Grupos Homogêneos inteiros podem ser caracterizados a partir da avaliação da exposição do EMR, sob circunstâncias adequadas.",
      "Exposto de Maior Risco é o trabalhador de um grupo homogêneo de exposição (GHE) que é julgado como possuidor da maior exposição relativa em seu grupo. O entendimento de “mais exposto” do grupo é dado no sentido qualitativo.",
      "A caracterização e determinação do EMR será dada por:",
      "a) por julgamento profissional",
      "A observação de campo, o conhecimento acurado das operações e das atividades, bem como a experiência e o conhecimento do profissional relativamente ao agente e à forma de exposição contribuem para determinação do EMR.",
      "O EMR será determinado por possuir uma ou mais das seguintes características, que lhe conferem o maior potencial de exposição:",
      "Exercer suas atividades mais próximo da fonte do agente;",
      "Exercer suas atividades em região do ambiente onde ocorre maior concentração ou intensidade aparente do agente;",
      "Exercer suas atividades de maneira a se expor por mais tempo ao agente;",
      "Exercer as rotinas operacionais (modus operandi) de forma a se expor mais ao agente.",
      "b) Por Ferramenta Estatística",
      "Outra forma de caracterizar o EMR está descrita no Manual de Estratégia de Amostragem da NIOSH, o qual apresenta uma ferramenta estatística para determinação do EMR, utilizando sorteio aleatório para realização das avaliações quantitativas num mesmo GHE.",
      "RISCOS OCUPACIONAISSão considerados riscos ocupacionais os agentes físicos, químicos, biológicos, Mecânicos (acidentes) e ergonômicos que, em função de sua natureza, concentração ou intensidade e tempo de exposição, podem ser capazes de causar danos à saúde e à integridade física do trabalhador.",
      "AGENTES FÍSICOSSão as diversas formas de energia a que possam estar expostos os trabalhadores. Devem ser considerados durante as avaliações, os agentes físicos que se apresentam nas seguintes formas de energia: ruído; vibração; pressões anormais; temperaturas extremas; radiações ionizantes; radiação não ionizantes; infrassom e ultrassom.",
      "AGENTES QUÍMICOSSão as substâncias, compostos ou produtos que possam penetrar no organismo pela via respiratória, nas formas de poeiras, fumos, névoas, neblinas, gases ou vapores, ou que, pela natureza da atividade de exposição, possam ter contato ou ser absorvido pelo organismo através da pele ou por ingestão.",
      "Para fins de desenvolvimento do PGR, a avaliação deverá contemplar todas aquelas substâncias existentes no processo produtivo, sendo que as avaliações quantitativas da exposição dos trabalhadores deverão considerar os valores dos limites previstos na NR-15 enquanto não forem estabelecidos os anexos da NR-9 ou, na ausência destes os valores limites de exposição ocupacional adotados pela American Conference of Governmental Industrial Hygienists - ACGIH, ou aqueles que venham a ser estabelecidos em negociação coletiva de trabalho, desde que mais rigorosos do que os critérios técnico-legais estabelecidos.",
      "AGENTES BIOLÓGICOSSão os Microorganismos e parasitas ou materiais originados de organismos que, em função de sua natureza e do tipo de exposição, são capazes de acarretar lesão ou agravo à saúde do trabalhador. Exemplos: bactéria Bacillus anthracis, vírus linfotrópico da célula T humana, príon agente de doença de Creutzfeldt-Jakob, fungo Coccidioides immitis.",
      "No desenvolvimento do PGR, serão consideradas as atividades em que os trabalhadores estão expostos a agentes biológicos.",
      "AGENTES MECÂNICOS / ACIDENTESão os potencialmente geradores de acidentes, como o arranjo físico deficiente; máquinas e equipamentos sem proteção; ferramentas inadequadas; ou defeituosas; eletricidade; incêndio ou explosão; animais peçonhentos; armazenamento inadequado, dentre outros.",
      "FATORES DE RISCOS ERGONÔMICOSSão todas as condições que afetam o bem-estar do indivíduo, sejam elas físicas, mentais ou organizacionais. Podem ser compreendidas como fatores que interferem nas características psicofisiológicas do profissional, provocando desconfortos e problemas de saúde. São exemplos de riscos ergonômicos: levantamento de peso, ritmo excessivo de trabalho, monotonia, repetitividade, postura inadequada.",
      "AVALIAÇÃO QUALITATIVAPara fins de normatização do Tipo de Exposição, não cabe apenas visualizar o tempo de exposição, mas se atentar também às condições do ambiente onde as atividades laborais são executadas e, principalmente, a natureza dos agentes, visando volume, fator de risco, intensidade e/ou concentração deles, além da nocividade presumida e independente de mensuração, constatada pela simples presença do agente no ambiente de trabalho, em conformidade com as normas técnicas aplicáveis.",
      "AVALIAÇÃO QUANTITATIVAA nocividade será considerada pela ultrapassagem dos limites de doses ou tolerância, em conformidade com as normas técnicas aplicáveis.",
    ],
  },
  {
    title: "13 - Etapas do Programa de Gerenciamento de Riscos",
    paragraphs: [
      "LEVANTAMENTO PRELIMINAR DE PERIGOSO levantamento preliminar de perigos deve ser realizado antes do início do funcionamento do estabelecimento ou novas instalações, para as atividades existentes e nas mudanças e introdução de novos processos ou atividades de trabalho.",
      "O levantamento preliminar de perigos e riscos deve ser realizado para identificar situações em que é possível evitar ou eliminar perigos; e identificar situações de risco ocupacional evidente nas quais a organização deve adotar medidas de redução ou controle imediatamente.",
      "Quando na fase de levantamento preliminar de perigos e riscos não for possível adotar medidas imediatas para reduzir ou controlar o risco ocupacional evidente, as medidas devem ser inseridas no plano de ação e o risco registrado no inventário de riscos.",
      "O responsável da organização deverá assegurar que toda modificação e/ou novo projeto a ser implantado seja avaliada preliminarmente com relação a identificação de perigos e avaliação dos riscos potencialmente presentes.",
      "IDENTIFICAÇÃO DOS PERIGOS E AVALIAÇÃO DOS RISCOS OCUPACIONAISA identificação dos perigos foi realizada por meio da caracterização dos processos desenvolvidos pelos trabalhadores, com informações sobre sua ocupação na organização, atividades que realizam, setores onde estão lotados, com o objetivo de estudar como eles se relacionam com os agentes (perigos) presentes nesses processos e no ambiente.",
      "A etapa de identificação de perigos deve incluir a descrição dos perigos e possíveis lesões ou agravos à saúde; identificação das fontes e/ou circunstâncias; e indicação do grupo de trabalhadores sujeitos ao perigo, que pode ser constituído por um ou mais trabalhadores.",
      "A identificação dos perigos deve abordar os perigos externos previsíveis relacionados ao trabalho que possam afetar a saúde e segurança no trabalho.",
      "Os processos realizados na organização foram mapeados por setor e/ou atividade, com o objetivo de identificar os grupos de trabalhadores expostos a fatores de risco similares. Os perigos foram inventariados e avaliados pelo Grupo de Homogêneo de Exposição (GHE).",
      "O Grupo de Homogêneo de Exposição (GHE) corresponde ao grupo de trabalhadores expostos de forma semelhante, de tal forma que a avaliação da exposição de qualquer trabalhador do grupo seja representativa da exposição de todos que pertencerem ao mesmo grupo.",
      "Após a identificação dos perigos realizou-se a avaliação qualitativa ou quantitativa dos riscos, conforme necessidade, para definição do nível de riscos e priorização de ações, podendo serem previstas novas avaliações quantitativas necessárias à avaliação ou ao seu controle. Os perigos reconhecidos nessa etapa foram incluídos no inventário, o qual encontra-se disponível no anexo “Inventário de Riscos Ocupacionais”.",
      "A organização deve avaliar os riscos ocupacionais relativos aos perigos identificados em seu estabelecimento, de forma a manter informações para adoção de medidas de prevenção. Para cada risco deve ser indicado o nível de risco ocupacional, determinado pela combinação da severidade das possíveis lesões ou agravos à saúde com a probabilidade de sua ocorrência.",
    ],
  },
  {
    title: "14 - Caracterização de Perigos e Critérios de Avaliação",
    paragraphs: [
      "CRITÉRIOS DE RISCO ADOTADOSA estimativa dos níveis de risco será realizada a partir dos índices de Probabilidade e Severidade dos danos potenciais, conforme a Matriz de Riscos.",
      "A avaliação de riscos é realizada por meio da análise do nível de risco da atividade/tarefa identificada. A Gradação do Risco considera o cruzamento da severidade que pode causar e a probabilidade do perigo, tanto para situações normais, quanto de emergências.",
      "MATRIZ DE RISCOSTrata-se de uma Matriz 5X5 (cinco colunas versus cinco linhas), que permite a classificação em cinco Níveis de Risco representados por cores: Irrelevante (verde claro); Baixo (Verde escuro); Moderado (Amarelo); Alto (Laranja) e Crítico (Vermelho).",
      "Para os Níveis de Risco classificados pela mesma cor, é possível identificar numericamente o prioritário para fins de prevenção e controle, através do produto obtido entre o cruzamento de Probabilidade X Severidade. Cada Nível de Risco possui uma interpretação que está relacionada com diferentes critérios para tomada de decisão da empresa. As referências técnicas utilizadas para embasar a Matriz de Riscos adotada pela empresa foram:",
      "Curso GRO FUNDACENTRO – dezembro/2020 (online);",
      "ISO 31.000",
      "3) Livro Segurança no Trabalho e Prevenção de Acidentes: uma abordagem holística (Autor: Benedito Cardella).",
      "SEVERIDADEA gradação da severidade deve ser estabelecida em razão da magnitude das possíveis consequências das lesões ou agravos à saúde. Cada nível é definido por uma palavra de interpretação, que são seguidos por textos técnicos que servem para auxiliar o profissional a encontrar a melhor gradação. Os critérios para gradação do Severidade foram divididos em duas classificações (Segurança; Saúde) e foram embasados nas melhores referências técnicas pesquisadas no momento da elaboração deste documento. O objetivo é permitir que diferentes profissionais possam chegar a conclusões similares na análise dos danos que podem ser provocados por um evento perigoso, pela exposição a agente nocivo ou pela exigência da atividade de trabalho.",
      "Para cada perigo identificado, quando existir mais de uma consequência possível, deve ser selecionada a consequência de maior magnitude.",
      "PROBABILIDADEA gradação de probabilidade de ocorrência de dano é determinada por um índice que varia entre Improvável, Remoto, Possível, Provável e Muito Provável, conforme critérios técnicos específicos. Para a avaliação da probabilidade de lesões ou agravos à saúde decorrentes de perigos físicos, químicos e biológicos, é necessário comparar o perfil de exposição ocupacional com valores de referência ou seguir os critérios estabelecidos na NR-09, considerando a eficácia das medidas de prevenção inovadoras. No caso dos fatores ergonômicos, incluindo os riscos psicossociais relacionados ao trabalho, a análise deve levar em conta a exigência da atividade laboral e a efetividade das medidas de controle. Já para os riscos decorrentes de acidentes, a probabilidade de ocorrência deve ser avaliada com base na exposição do trabalhador ao perigo e na eficiência das medidas de prevenção adotadas. Essa abordagem permite uma estimativa mais precisa dos níveis de risco, garantindo maior confiabilidade no gerenciamento de riscos ocupacionais.",
      "(*) Refere-se a avaliações quantitativas eventualmente disponíveis e que representam adequadamente o Perfil de Exposição sob os critérios técnicos de Estratégia de Amostragem. Na ausência de avaliações quantitativas representativas sugere-se o uso inicial dos critérios de \"Situação não Quantificada\"",
      "Nota: Critérios aplicáveis para avaliar exposições em que não há intenção deliberada de manipular ou de trabalhar com agentes biológicos, mas onde a exposição é possível dada a natureza da atividade.",
    ],
  },
  {
    title: "15 - Gradação do Risco",
    paragraphs: [
      "Com o resultado das probabilidades e gradação do Severidade é realizado o cruzamento para definir o nível de risco ocupacional determinado pela combinação dos dados. Assim a empresa poderá classificar cada risco ocupacional relativo aos perigos identificados em seu estabelecimento. Logo abaixo o quadro demonstra a descrição para cada item:",
      "A combinação da severidade com a probabilidade de o potencial de um perigo ocorrer, no pior cenário verossímil possível.",
      "ESTABELECIMENTO DE PRIORIDADES E METAS DE AVALIAÇÃO E CONTROLENeste PGR a priorização das medidas de controle, caso sugeridas, será definida conforme a categorização de risco estabelecida pela metodologia de graduação de riscos baseada em MULHAUSEN & DAMIANO e nas diretrizes da AIHA (American Industrial Hygiene Association). A matriz de prioridades apresentada neste tópico orienta a definição das ações preventivas a serem adotadas, considerando a gradação do risco e o número de trabalhadores possivelmente afetados. Dessa forma, os riscos classificados com maior criticidade terão prioridade na implementação das medidas de controle.",
      "De acordo com o levantamento dos dados para execução do PGR, será elaborado um Plano de ação contemplando atividades, metas e prioridades a serem implementadas de forma a eliminar, minimizar ou controlar os riscos ocupacionais.",
      "Caso a tabela indique que para determinado risco não é necessário realizar uma ação específica, mas a empresa venha a receber uma autuação de organismo fiscalizador, ou venha acontecer algum acidente em decorrência do perigo relacionado ao risco, deve-se realizar alguma ação para minimizar esse risco, independente do resultado obtido na tabela.",
      "O plano de ação deve ser amplo e deve atender às reais necessidades de melhoria da empresa, não se prendendo somente às exigências da NR-1.",
      "AVALIAÇÃO DOS RISCOS OCUPACIONAIS E DA EXPOSIÇÃO Envolve o monitoramento dos riscos ocupacionais para a determinação da intensidade dos agentes físicos e a concentração dos agentes químicos, visando o dimensionamento da exposição dos trabalhadores.",
      "A avaliação quantitativa deverá ser realizada sempre que necessária para comprovar o controle da exposição aos agentes identificados no reconhecimento, dimensionar a exposição ocupacional dos grupos de trabalhadores e subsidiar o equacionamento das medidas de prevenção.",
      "IMPLANTAÇÃO DE MEDIDAS DE CONTROLE E AVALIAÇÃO DA EFICÁCIA Envolve a adoção de medidas necessárias e suficientes para a eliminação ou redução dos riscos ambientais.",
      "As medidas preventivas serão obrigatórias sempre que for atingido o nível de ação para os agentes físicos e químicos, definido no próximo item, incluindo o monitoramento periódico, informação aos trabalhadores e o controle médico.",
      "O PGR será de abrangência e profundidade gradual às características dos riscos e das necessidades de controle.",
      "Deverão ainda ser propostas medidas necessárias e suficientes para a eliminação, minimização ou controle dos riscos ocupacionais, sempre que for verificada uma ou mais das seguintes situações:",
      "Riscos potenciais na fase de antecipação;",
      "Quando forem constatados riscos evidentes a saúde na fase de reconhecimento;",
      "Quando os resultados das avaliações quantitativas forem superiores aos valores limites previstos na NR-15 ou na American Conference of Governmental Industrial Hygienists - ACGIH;",
      "Quando, após a avaliação quantitativa dos agentes, for constatada exposição acima dos Níveis de ação, quais sejam: para agentes químicos, metade dos Limites de Tolerância; para ruído, a dose de 0,5;",
      "Houver evidências de associação, por meio do controle médico da saúde, entre as lesões e os agravos à saúde dos trabalhadores com os riscos e as situações de trabalhos identificados;",
      "Na ocorrência de acidentes ou doenças relacionadas ao trabalho;",
      "Exigências previstas em Normas Regulamentadoras e nos dispositivos legais determinarem;",
      "A classificação dos riscos ocupacionais assim determinar.",
      "As medidas de controle a serem implantadas obedecerão a ordem de prioridade:",
      "Eliminação dos fatores de risco;",
      "Minimização e controle dos fatores de riscos, com a adoção de medidas de proteção coletiva;",
      "Minimização e controle dos fatores de riscos, com adoção de medidas administrativas ou de organização do trabalho; e",
      "Adoção de medidas de proteção individual.",
      "Quando comprovada pela organização a inviabilidade técnica da adoção de medidas de proteção coletiva, ou quando estas não forem suficientes ou encontrarem-se em fase de estudo, planejamento ou implantação ou, ainda, em caráter complementar ou emergencial, deverão ser adotadas outras medidas, obedecendo-se a seguinte hierarquia:",
      "Medidas de caráter administrativo ou de organização do trabalho;",
      "Utilização de Equipamento de Proteção Individual – EPI.",
      "O emprego do EPI deverá ser adotado de acordo com as determinações da NR-6 – Equipamentos de Proteção Individual. Vale ressaltar que os EPI que porventura sejam utilizados pelos trabalhadores durante o desenvolvimento das atividades serão mencionados no Anexo 1 – Reconhecimento dos Riscos.",
      "As medidas de controle deverão ser previstas no Plano de Ação, constante do PGR, após consenso com o responsável pela implementação deste programa.",
      "Seguem alguns exemplos de medidas de controle a serem consideradas:",
      "Substituição do agente agressivo;",
      "Mudança ou alteração do processo ou operação",
      "Enclausuramento da fonte;",
      "Segregação do processo ou operação;",
      "Modificação de projetos;",
      "Limitação do tempo de exposição;",
      "Utilização de equipamento de proteção individual – EPI;",
      "Outras.",
      "O CONTROLE existente e ou sugerido será apresentado no quadro da avaliação de cada GHE, onde também será mencionada a sua eficácia e o grau de prioridade para ação sugerida.",
      "MONITORAMENTO DA EXPOSIÇÃO DO RISCO Quando detectada alguma exposição à saúde dos empregados, será comunicado ao Médico do Trabalho coordenador do PCMSO, para as devidas providências. Da mesma forma, toda vez que houver suspeita médica com relação à exposição ambiental, o Médico do Trabalho responsável pelo PCMSO deverá acionar o técnico responsável pelo PGR, para as avaliações e sugestões de controles necessários à eliminação, redução a níveis toleráveis de exposição e/ou aplicação de medidas de proteção aos empregados.",
      "REGISTRO, MANUTENÇÃO E DIVULGAÇÃO DOS DADOS Registro: Os registros dos dados serão feitos através de avaliações, levantamentos e monitoramento dos riscos que foram levantados na antecipação das atividades do que os colaboradores possam estar expostos e registrados neste programa; O registro de dados deverá estar sempre disponível aos trabalhadores interessados ou seus representantes e permitir o imediato acesso para as autoridades competentes.",
      "Manutenção: O inventário de riscos ocupacionais deve ser mantido atualizado, o histórico de atualizações do Programa de Gerenciamento de Risco – PGR e os documentos que o compõem, devem ser mantidos por um período mínimo de 20 anos ou pelo período estabelecido em normatização específica, os documentais com histórico de revisões devem ser devidamente assinados e datados.",
      "Divulgação: Os empregadores divulgarão aos trabalhadores de maneira apropriada através de meios eletrônicos ou informativos sobre os riscos ocupacionais que possam originar-se nos locais de trabalho e sobre os meios disponíveis para prevenir ou limitar tais riscos e para proteger-se dos mesmos.",
      "PERIODICIDADE E FORMA DE AVALIAÇÃO DO PGR",
      "O inventário de riscos ocupacionais deve ser mantido atualizado.",
      "A avaliação de riscos deve constituir um processo contínuo, o PGR será revisto a cada dois anos ou sempre que necessário quando da ocorrência das seguintes situações:",
      "Após implementação das medidas de prevenção, para avaliação de riscos residuais;",
      "Após inovações e modificações nas tecnologias, ambientes, processos, condições, procedimentos e organização do trabalho que impliquem em novos riscos ou modifiquem os riscos existentes;",
      "Quando identificadas inadequações, insuficiências ou ineficácias das medidas de prevenção;",
      "Na ocorrência de acidentes ou doenças relacionadas ao trabalho;",
      "Quando houver mudança nos requisitos legais aplicáveis.",
      "Observação: No caso de organizações que possuírem certificação em sistema de gestão de SST, o prazo poderá ser de até 3 (três) anos.",
      "A avaliação do PGR ocorrerá considerando:",
      "Os agravos à saúde aos trabalhadores envolvidos no PGR. O PCMSO em seu relatório analítico apresenta esses tipos de informação.",
      "O cumprimento do Plano de ação, suas metas e prioridades (se existente);",
      "Implementação das Medidas de Controle.",
    ],
  },
  {
    title: "15 - Plano de Ação com Metas e Forma de Acompanhamento",
    paragraphs: [
      "O Plano inclui todas as atividades identificadas nas fases de reconhecimento, avaliação dos riscos ou definidas como medidas de prevenção. Os responsáveis e prazos de cada atividade deverão ser definidos em consenso com o responsável pelo estabelecimento ou posto de trabalho.",
      "Após os levantamentos e conclusões, devem ser relacionadas no cronograma em anexo, as metas estabelecidas, bem como o planejamento para o cumprimento destas metas.",
    ],
  },
  {
    title: "16 - Relação de Prestação de Serviços a Terceiros",
    paragraphs: [
      "No Gerenciamento de Riscos Ocupacionais (GRO) em prestação de serviços a terceiros, conforme o subitem 1.5.8 da NR-01, o PGR da contratante deve incluir medidas de prevenção para as contratadas que atuem em suas dependências ou locais convencionados. Caso utilize o PGR da contratada, esta deve fornecer o inventário de riscos e o plano de ação. Além disso, ambas devem informar reciprocamente os riscos que possam impactar suas atividades. Quando houver interação entre operações, as medidas de prevenção devem ser definidas em conjunto, sob coordenação da contratante, garantindo um ambiente de trabalho seguro.",
      "RECOMENDAÇÕES GERAISRessalte-se que os trabalhadores interessados terão o direito de apresentar propostas e receber informações e orientações a fim de assegurar a proteção aos riscos ocupacionais identificados na execução do PGR.",
      "O empregador deverá garantir que, na ocorrência de riscos ocupacionais nos locais de trabalho que coloquem em situação de grave e iminente risco um ou mais trabalhadores, eles possam interromper de imediato as suas atividades, comunicando o fato ao superior hierárquico direto para as devidas providências.",
    ],
  },
  {
    title: "17 - Exames, Discussão do Plano de Ação e Considerações Finais",
    paragraphs: [
      "O principal objetivo deste trabalho foi fornecer dados sobre a exposição ocupacional a que estão sujeitos os trabalhadores.",
      "A responsabilidade técnica do presente documento, que foi confeccionado pelos profissionais assinados ao final, restringe-se exclusivamente às avaliações e recomendações realizadas pelo mesmo, ficando sob inteira responsabilidade da Empresa a implantação e acompanhamento das medidas de proteção.",
      "As Conclusões deste programa referem-se a avaliações de riscos realizadas no ambiente de trabalho, baseadas nas informações (Relação de funcionários, descritivos de funções, descrição dos métodos de trabalhos) prestadas pela empresa. Caberá a ela sempre informar situações como mudanças de processo, equipamentos, ferramentas de trabalho, arranjo físico ou outras situações possam gerar riscos aos trabalhadores, solicitando nova avaliação dos agentes citados neste programa.",
    ],
  },
  {
    title: "18 - Assinatura",
    paragraphs: [
      "Rio de Janeiro, xx de xxxxxxx de xxxx.",
    ],
  },
];
